name: Pull Request

on:
  pull_request_target:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
      - 'docs/'
      - 'examples/'
      - 'hack/'
      - 'config/'
env:
  DOCKER_FILE_PATH: Dockerfile
  GOLANG_VERSION: 1.18
  HELM_VERSION: v3.8.2
  KIND_VERSION: "v0.17.0"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pull Request

    steps:
    - name: Check out code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v6.0.2
      with:
        ref: ${{github.event.pull_request.head.sha}}

    - name: Set up Go
      uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
      with:
        go-version: ${{ env.GOLANG_VERSION }}

    - name: Lint
      uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v9.2.0
      with:
        version: v1.50.1
        only-new-issues: false
        args: --timeout 10m

    # Set up helm binary
    - name: Set up Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
      with:
        version: ${{ env.HELM_VERSION }}

    - name: Helm Lint
      run: |
        helm lint charts/ingressmonitorcontroller

    - name: Install kind
      uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
      with:
        version:  ${{ env.KIND_VERSION }}

    - name: Check cluster info
      run: |
        kubectl version --short --client
        kind version
        kind version | grep -q ${KIND_VERSION}

    - name: Set up Cluster
      run: |
        kubectl cluster-info
        make install
        mkdir -p .local
        echo "${{ secrets.SECRET_KUBERNETES_RESOURCES }}" | base64 --decode > .local/test-config.yaml

    - name: Test
      run: make test

    - name: Generate Tag
      id: generate_tag
      run: |
        sha=${{ github.event.pull_request.head.sha }}
        tag="SNAPSHOT-PR-${{ github.event.pull_request.number }}-${sha:0:8}"
        echo "GIT_TAG=$(echo ${tag})" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v4.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v4.0.0
      with:
        driver-opts: |
            image=moby/buildkit:v0.9.3
        buildkitd-flags: --debug

    - name: Login to Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v4.1.0
      with:
        username: ${{ secrets.STAKATER_DOCKERHUB_USERNAME }}
        password: ${{ secrets.STAKATER_DOCKERHUB_PASSWORD }}

    - name: Generate image repository path
      run: |
        echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v7.0.0
      with:
        context: .
        file: ${{ env.DOCKER_FILE_PATH  }}
        pull: true
        push: true
        cache-to: type=inline
        tags: |
          ${{ env.IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.GIT_TAG }}
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Comment on PR
      uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v3.10.0
      if: always()
      env:
       GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
      with:
        message-success: '@${{ github.actor }} Image is available for testing. `docker pull ${{ env.IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.GIT_TAG }}`'
        message-failure: '@${{ github.actor }} Yikes! You better fix it before anyone else finds out! [Build](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}/checks) has Failed!'
        allow-repeats: false

    - name: Notify Slack
      uses: 8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e # v3.19.0
      if: always() # Pick up events even if the job fails or is canceled.
      with:
        status: ${{ job.status }}
        fields: repo,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
