name: Push

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/'
      - 'examples/'
      - 'hack/'
      - 'config/'

env:
  DOCKER_FILE_PATH: Dockerfile
  BUNDLE_DOCKER_FILE_PATH: bundle.Dockerfile
  GOLANG_VERSION: 1.18
  OPERATOR_SDK_VERSION: "1.19.0"
  KUSTOMIZE_VERSION: "4.5.7"
  KUBERNETES_VERSION: "1.23.5"
  KIND_VERSION: "v0.17.0"
  HELM_REGISTRY_URL: "https://stakater.github.io/stakater-charts"
  HELM_VERSION: v3.8.2

jobs:
  build:
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    - name: Set up Go
      uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
      with:
        go-version: ${{ env.GOLANG_VERSION }}

    - name: Lint
      uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
      with:
        version: v1.50.1
        only-new-issues: false
        args: --timeout 10m

    # Set up helm binary
    - name: Set up Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
      with:
        version: ${{ env.HELM_VERSION }}

    - name: Helm Lint
      run: |
        helm lint charts/ingressmonitorcontroller

    - name: Install kind
      uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
      with:
        version:  ${{ env.KIND_VERSION }}

    - name: Check cluster info
      run: |
        kubectl version --short --client
        kind version
        kind version | grep -q ${KIND_VERSION}

    - name: Set up Cluster
      run: |
        kubectl cluster-info
        make install
        mkdir -p .local
        echo "${{ secrets.SECRET_KUBERNETES_RESOURCES }}" | base64 --decode > .local/test-config.yaml

    - name: Test
      run: make test

    - name: Generate Tag
      id: generate_tag
      uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42 # 1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        DRY_RUN: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
      with:
        driver-opts: |
            image=moby/buildkit:v0.9.3
        buildkitd-flags: --debug

    - name: Login to Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        username: ${{ secrets.STAKATER_DOCKERHUB_USERNAME }}
        password: ${{ secrets.STAKATER_DOCKERHUB_PASSWORD }}

    - name: Generate image repository path
      run: |
        echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
      with:
        context: .
        file: ${{ env.DOCKER_FILE_PATH  }}
        pull: true
        push: true
        cache-to: type=inline
        tags: |
          ${{ env.IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.new_tag }}
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.revision=${{ github.sha }}

    ##############################
    ## Add steps to generate required artifacts for a release here(helm chart, operator manifest etc.)
    ##############################

    # Generate tag for operator without "v"
    - name: Generate Operator Tag
      id: generate_operator_tag
      uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42 # 1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        DRY_RUN: true

    # Install operator-sdk
    - name: Install operator-sdk
      uses: redhat-actions/openshift-tools-installer@144527c7d98999f2652264c048c7a9bd103f8a82 # v1.13.1
      with:
        source: "github"
        operator-sdk: ${{ env.OPERATOR_SDK_VERSION }}

    # Install kustomize
    - name: Install kustomize
      uses: imranismail/setup-kustomize@2ba527d4d055ab63514ba50a99456fc35684947f # v2.1.0
      with:
        kustomize-version: ${{ env.KUSTOMIZE_VERSION }}

    - name: Generate Bundle
      env:
        VERSION: ${{ steps.generate_operator_tag.outputs.new_tag }}
        IMG: ${{ env.IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.new_tag }}
      run: make bundle

    - name: Verify bundle
      run: operator-sdk bundle validate ./bundle --select-optional name=operatorhub

    - name: Build and push Bundle Image
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
      with:
        context: .
        file: ${{ env.BUNDLE_DOCKER_FILE_PATH  }}
        pull: true
        push: true
        cache-to: type=inline
        tags: |
          ${{ env.IMAGE_REPOSITORY }}-bundle:${{ steps.generate_tag.outputs.new_tag }}
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.revision=${{ github.sha }}

    # Update chart tag to the latest semver tag
    - name: Update Chart Version
      env:
        VERSION: ${{ steps.generate_operator_tag.outputs.new_tag }}
      run: make bump-chart

    - name: Update Chart CRDs
      run: make generate-crds

    # Publish helm chart
    - name: Publish Helm chart
      uses: stefanprodan/helm-gh-pages@89c6698c192e70ed0e495bee7d3d1ca5b477fe82 # master
      with:
        branch: master
        repository: stakater-charts
        target_dir: docs
        token: ${{ secrets.STAKATER_GITHUB_TOKEN }}
        charts_dir: charts/
        charts_url: ${{ env.HELM_REGISTRY_URL }}
        owner: stakater
        linting: on
        commit_username: stakater-user
        commit_email: stakater@gmail.com

    # Commit back changes
    - name: Commit files
      run: |
        git config --local user.email "stakater@gmail.com"
        git config --local user.name "stakater-user"
        git status
        git add .
        git commit -m "[skip-ci] Update artifacts" -a

    - name: Push changes
      uses: ad-m/github-push-action@4cc74773234f74829a8c21bc4d69dd4be9cfa599 # master
      with:
        github_token: ${{ secrets.STAKATER_GITHUB_TOKEN }}

    # Push Latest Tag
    - name: Push Latest Tag
      uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42 # 1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: Notify Slack
      uses: 8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e # v3.19.0
      if: always() # Pick up events even if the job fails or is canceled.
      with:
        status: ${{ job.status }}
        fields: repo,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
